---
  - name: NSO_CONFIG MODULE
    hosts: localhost
    gather_facts: no 

    tasks:  
    - name: IMPORT CREDS
      include_vars:
        file: creds.yml

    - name: CREATE DEVICE IN NSO
      cisco.nso.nso_config:
        url: "http://{{ nso_hostname }}/jsonrpc"
        username: "{{ nso_username }}"
        password: "{{ nso_password }}"
        data:
          tailf-ncs:devices:
            device:
            - address: "{{ item }}"
              name: "{{ item }}"
              authgroup: "default"
              device-type:
                cli:
                  ned-id: "cisco-nx-cli-3.0"
              port: "22"
              state:
                admin-state: "unlocked"
      loop: "{{ devices }}"